/* =================================================================
| PlasmaBallCharacter.h  --  Ion_Cortex
|
| Created by Jack on 10/10/2023
| Copyright © 2023 jacktogon. All rights reserved.
================================================================= */

#pragma once

#include "CoreMinimal.h" // includes a minimal set of core classes required by most source files in Unreal
#include "GameFramework/Character.h" // related to the basic character class in Unreal, allowing movement, animation, etc.
// Additional includes for Niagara
#include "NiagaraComponent.h"
#include "NiagaraSystem.h"
#include "NiagaraFunctionLibrary.h"
#include "PlasmaBallCharacter.generated.h" // a file generated by the Unreal Header Tool (UHT) when compiling. It handles things like reflection, which allows C++ code to be exposed to and interact with the Unreal Editor


UCLASS() // unreal macro
class ION_CORTEX_API APlasmaBallCharacter : public ACharacter
{
    GENERATED_BODY()

public:
    // Sets default values for this character's properties
    APlasmaBallCharacter();

    /*
    * can be seen but not modified in the editor;
    * can be accessed in Blueprints (Unreal's visual scripting language) but can't be modified
    * will be sorted under the "Mesh" category
    * meta = (AllowPrivateAccess = "true"): This property, although private, can be edited in derived Blueprint classes.
    */ 
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = Mesh, meta = (AllowPrivateAccess = "true"))
    class UStaticMeshComponent* SphereMesh;



    // Variable to hold the Niagara system asset
    UPROPERTY(EditDefaultsOnly, Category = "FX")
    UNiagaraSystem* PlasmaEmitter;

    // Variable to hold the Niagara component at runtime
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "FX", meta = (AllowPrivateAccess = "true"))
    UNiagaraComponent* PlasmaEmitterComponent;

protected:
    // Called when the game starts or when spawned
    virtual void BeginPlay() override;

    // Camera boom positioning the camera behind the character
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = Camera, meta = (AllowPrivateAccess = "true"))
    class USpringArmComponent* CameraBoom;

    // main camera component associated with this character
    UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = Camera, meta = (AllowPrivateAccess = "true"))
    class UCameraComponent* FollowCamera;

public:
    // Called every frame. it's used to frequently update or check something in the game
    virtual void Tick(float DeltaTime) override;

    // Binds input functions (like pressing a key) to actions.
    virtual void SetupPlayerInputComponent(class UInputComponent* PlayerInputComponent) override;

    void MoveForward(float Value);
    void MoveRight(float Value);
};
